services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=user
      - POSTGRES_DB=coinapi
    ports:
      - '5433:5432'